# -*- coding: utf-8 -*-
"""Cnn_GUI.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdTqtzBTUo0BNcvIa9h1BJGH7MgDjPPb
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import gradio as gr
from PIL import Image


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)


SIZE, BATCH, EPOCHS = 128, 32, 5


train_tf = transforms.Compose([
    transforms.Resize((SIZE, SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([.485,.456,.406],[.229,.224,.225])
])

test_tf = transforms.Compose([
    transforms.Resize((SIZE, SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([.485,.456,.406],[.229,.224,.225])
])


train_ds = datasets.OxfordIIITPet(
    "./data", split="trainval", target_types="category",
    transform=train_tf, download=True
)

test_ds = datasets.OxfordIIITPet(
    "./data", split="test", target_types="category",
    transform=test_tf, download=True
)

classes = train_ds.classes

train_loader = DataLoader(train_ds, BATCH, shuffle=True, num_workers=2)
test_loader = DataLoader(test_ds, BATCH, shuffle=False, num_workers=2)

print("Classes:", len(classes))



class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv2d(3,32,3,padding=1), nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32,64,3,padding=1), nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64,128,3,padding=1), nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(128,256,3,padding=1), nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),

            nn.Flatten(),
            nn.Linear(256,37)
        )

    def forward(self,x):
        return self.net(x)


model = CNN().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)



for epoch in range(EPOCHS):

    model.train()
    correct = total = 0

    for x,y in train_loader:

        x,y = x.to(device),y.to(device)

        optimizer.zero_grad()

        out = model(x)

        loss = criterion(out,y)

        loss.backward()
        optimizer.step()

        correct += (out.argmax(1)==y).sum().item()
        total += y.size(0)

    print(
        f"Epoch {epoch+1}/{EPOCHS} "
        f"Accuracy: {100*correct/total:.2f}%"
    )



model.eval()
correct = total = 0

with torch.no_grad():

    for x,y in test_loader:

        x,y = x.to(device),y.to(device)

        out = model(x)

        correct += (out.argmax(1)==y).sum().item()
        total += y.size(0)

accuracy = 100*correct/total

print(f"\nTest Accuracy: {accuracy:.2f}%")



torch.save(model.state_dict(),"pet_cnn.pth")



def predict(image):

    image = Image.fromarray(image).convert("RGB")

    x = test_tf(image).unsqueeze(0).to(device)

    with torch.no_grad():
        prob = torch.softmax(model(x),1)[0]

    values, indices = torch.topk(prob,5)

    return {
        classes[i.item()]: v.item()
        for v,i in zip(values,indices)
    }


demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="numpy",label="Upload Pet Image"),
    outputs=gr.Label(num_top_classes=5),
    title=" Pet Breed Classifier",
    description="Upload a cat or dog image to predict its breed."
)

demo.launch(share=True)